const ROSTER=["Adam Kusiak","Brittany Johnson","David Lopez","Douglas Parker","Eber Serrano","Edwin Tejada","Jimmy Gravlee","Joel Tejada","Josue Gutierrez","Kevin Ardon","Patrick Davis","Robert Recinos","Yailyn Campos"];
function norm(h){return String(h||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function col(headers,names){const a=headers.map(h=>[h,norm(h)]);for(const x of names){const n=norm(x);let f=a.find(([h,v])=>v===n)||a.find(([h,v])=>v.includes(n)||n.includes(v));if(f)return f[0];}return null}
function maps(rows){const h=rows[0]?Object.keys(rows[0]):[];return{id:col(h,['ticket id','ticket number','ticket','request number','work item id']),locator:col(h,['assigned locator','assigned to','locator','employee','technician','completed by','name']),requestType:col(h,['request type','ticket type','call type','type']),workType:col(h,['work type','nature of work','work description','activity','job type']),dueDate:col(h,['due date','due time','response due','locate due']),late:col(h,['completed late','late completed','is late','was late','late','late flag']),remarks:col(h,['remarks','notes','description','comments'])}}
function tmap(rows){const h=rows[0]?Object.keys(rows[0]):[];return{name:col(h,['employee name','employee','name','locator','technician']),hours:col(h,['total hours','hours','worked hours','duration']),clockIn:col(h,['clock in','start time','time in']),clockOut:col(h,['clock out','end time','time out'])}}
function uniq(rows,id){if(!id)return rows;const s=new Set(),o=[];for(const r of rows){const v=String(r[id]||'').trim();if(!v||!s.has(v)){if(v)s.add(v);o.push(r)}}return o}
function late(v){v=String(v||'').trim().toLowerCase();if(['1','true','yes','y','late'].includes(v))return true;if(['0','false','no','n','on time','ontime'].includes(v))return false;return null}
function num(v){const n=Number(String(v||'').replace(/[^0-9.\-]/g,''));return isFinite(n)?n:0}
function name(v){v=String(v||'').trim().replace(/\s+/g,' ');let low=v.toLowerCase();return ROSTER.find(n=>n.toLowerCase()===low)||ROSTER.find(n=>{let p=n.toLowerCase().split(/\s+/);return low.includes(p[0])&&low.includes(p[p.length-1])})||v}
function count(rows,c){const o={};if(!c)return o;rows.forEach(r=>{const v=String(r[c]||'Blank').trim()||'Blank';o[v]=(o[v]||0)+1});return Object.fromEntries(Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,12))}
function calc(data){const comp=data.completed||[],open=data.open||[],time=data.time||[];const cm=maps(comp),om=maps(open),tm=tmap(time);const cu=uniq(comp,cm.id),ou=uniq(open,om.id);let byH={};if(tm.name){time.forEach(r=>{let n=name(r[tm.name]);byH[n]=(byH[n]||0)+num(r[tm.hours])})}let totalHours=Object.values(byH).reduce((a,b)=>a+b,0);let completedCount=cu.length,openCount=ou.length;let on=0,lateCount=0,cotpAvailable=false;if(cm.late){cu.forEach(r=>{let l=late(r[cm.late]);if(l===true){lateCount++;cotpAvailable=true}else if(l===false){on++;cotpAvailable=true}})}let byC={},byO={};if(cm.locator)cu.forEach(r=>{let n=name(r[cm.locator]);byC[n]=(byC[n]||0)+1});if(om.locator)ou.forEach(r=>{let n=name(r[om.locator]);byO[n]=(byO[n]||0)+1});let locatorRows=ROSTER.map(n=>{let h=byH[n]||0,c=byC[n]||0;return{name:n,hours:h,completed:c,openQueue:byO[n]||0,tph:h?c/h:0}});return{completedCount,openCount,totalHours,tph:totalHours?completedCount/totalHours:0,cotpAvailable,onTimeCompleted:on,lateCompleted:lateCount,cotp:cotpAvailable?(on/(on+lateCount))*100:0,lateRisk:0,ticketTypes:count(cu,cm.requestType),workTypes:count(cu,cm.workType),locatorRows}}
module.exports={calc};
